1st homework
hcp4715/R4Psy pull request #132
Opened 2024-04-10 11:09 UTC by Clairelee01090

2024-04-14 13:15 UTC, hcp4715 requested changes
这里多了一个叫git的文件？

2024-04-15 01:17 UTC, Clairelee01090 commented
前面push的时候可能多push了一个文件，我重新push一下看看



在 2024-04-14 21:15:48，"Hu Chuan-Peng" ***@***.***> 写道：

@hcp4715 requested changes on this pull request.

这里多了一个叫git的文件？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-04-15 15:19 UTC, hcp4715 commented
好像没有变化？“git”文件还是在

2024-04-16 02:52 UTC, hcp4715 commented
你重新pull request一个，修改只在`homeworks/2024`文件夹里新增txt，不做任何其他的修改

2024-04-16 02:53 UTC, closed without merging

2024-04-16 07:22 UTC, Clairelee01090 commented
好的，我重新提交一个request