1st homework
hcp4715/R4Psy pull request #134
Opened 2024-04-10 13:20 UTC by RRNNU

learning how to do 1st homework

2024-04-14 13:12 UTC, hcp4715 approved these changes

2024-04-14 13:14 UTC, hcp4715 requested changes
R4PsyBook与R4Psy是两个并行的项目，放在两个并行的文件夹比较好

2024-04-15 01:29 UTC, RRNNU commented
好的，谢谢老师！


---Original---
From: &quot;Hu ***@***.***&gt;
Date: Sun, Apr 14, 2024 21:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hcp4715/R4Psy] 1st homework (PR #134)




 
@hcp4715 requested changes on this pull request.
 
R4PsyBook与R4Psy是两个并行的项目，放在两个并行的文件夹比较好
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2024-04-16 02:51 UTC, hcp4715 commented
你重新pull request一下，修改应该只是针对`homeworks/2024`这个文件的，没有其他的修改。

2024-04-16 02:51 UTC, closed without merging

2024-04-16 04:12 UTC, RRNNU commented
好的，谢谢老师！我已重新pull&nbsp;request，R4PsyBook和R4Pys现在是并行文件夹


---Original---
From: &quot;Hu ***@***.***&gt;
Date: Tue, Apr 16, 2024 10:52 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hcp4715/R4Psy] 1st homework (PR #134)




 
你重新pull request一下，修改应该只是针对homeworks/2024这个文件的，没有其他的修改。
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;